// SPDX-License-Identifier: MIT
// Type shapes for the device catalog JSON.
//
// Generated by scripts/build-catalog.mjs from pencilresearch/midi CSV data.
// See docs/device-catalog.md for the design; see THIRD-PARTY-NOTICES.md for
// the upstream CC-BY-SA-4.0 attribution.

export type Orientation = '0-based' | 'centered';

export interface Range {
  min: number;
  max: number;
}

export interface NRPN {
  msb: number;
  lsb: number;
  range: Range;
  default: number | null;
}

export interface Parameter {
  /** Optional group name from the device manual (e.g. "Oscillator", "Filter"). */
  section: string | null;

  /** Human-readable parameter name (e.g. "Filter Cutoff", "LFO Rate"). */
  name: string;

  /** Long-form description from the device manual; often null. */
  description: string | null;

  /** CC number (cc_msb). null if this parameter is NRPN-only or otherwise non-CC-addressable. */
  cc: number | null;

  /** Valid CC value range. Defaults to {min: 0, max: 127} when not documented. */
  ccRange: Range;

  /** Sensible default ("neutral") value, if documented. null otherwise. */
  ccDefault: number | null;

  /** "0-based" (slider 0→max) or "centered" (knob −half→+half). Defaults to "0-based". */
  orientation: Orientation;

  /** Free-text value semantics, e.g. "0: Off; 1: On" or "0: Sine; 1: Saw; 2: Square". */
  usage: string | null;

  /** Errata, caveats, manual references. */
  notes: string | null;

  /** NRPN data preserved from upstream for future v2 support; the library does not act on this in v1. */
  nrpn: NRPN | null;
}

export interface Device {
  /** Manufacturer name as recorded upstream (e.g. "KORG", "Moog"). */
  manufacturer: string;

  /** Device name as recorded upstream (e.g. "volca bass", "NTS-1"). */
  device: string;

  /** Filesystem-safe identifier, lowercase, hyphenated (e.g. "korg-volca-bass"). */
  slug: string;

  /** All documented parameters for this device. */
  parameters: Parameter[];
}
