// AUTO-GENERATED by scripts/build-catalog.mjs — DO NOT EDIT BY HAND.
// Source CSVs vendored under vendor/pencilresearch-midi/.
// License: CC-BY-SA-4.0 (see THIRD-PARTY-NOTICES.md).
// Regenerate via: npm run build:catalog

import type { Device } from './MidiBleepBop';

/** All devices bundled with the library, keyed by slug (e.g. "korg-volca-bass"). */
export const DEVICES: Record<string, Device> = {
  // Source: vendor/pencilresearch-midi/KORG/volca bass.csv
  "korg-volca-bass": {
    "manufacturer": "KORG",
    "device": "volca bass",
    "slug": "korg-volca-bass",
    "parameters": [
      {
        "section": "General",
        "name": "Slide time",
        "description": null,
        "cc": 5,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Expression",
        "description": null,
        "cc": 11,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Octave",
        "description": null,
        "cc": 40,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "LFO rate",
        "description": null,
        "cc": 41,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "LFO intensity",
        "description": null,
        "cc": 42,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "VCO pitch 1",
        "description": null,
        "cc": 43,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "VCO pitch 2",
        "description": null,
        "cc": 44,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "VCO pitch 3",
        "description": null,
        "cc": 45,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "EG attack",
        "description": null,
        "cc": 46,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "EG decay/release",
        "description": null,
        "cc": 47,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Cutoff EG intensity",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Gate time",
        "description": null,
        "cc": 49,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      }
    ]
  },

  // Source: vendor/pencilresearch-midi/KORG/volca beats.csv
  "korg-volca-beats": {
    "manufacturer": "KORG",
    "device": "volca beats",
    "slug": "korg-volca-beats",
    "parameters": [
      {
        "section": "Levels",
        "name": "Kick level",
        "description": null,
        "cc": 40,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Snare level",
        "description": null,
        "cc": 41,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Lo tom level",
        "description": null,
        "cc": 42,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Hi tom level",
        "description": null,
        "cc": 43,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Closed hat level",
        "description": null,
        "cc": 44,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Open hat level",
        "description": null,
        "cc": 45,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Clap level",
        "description": null,
        "cc": 46,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Claves level",
        "description": null,
        "cc": 47,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Agogo level",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Levels",
        "name": "Crash level",
        "description": null,
        "cc": 49,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "PCM speed",
        "name": "Clap PCM speed",
        "description": null,
        "cc": 50,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "PCM speed",
        "name": "Claves PCM speed",
        "description": null,
        "cc": 51,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "PCM speed",
        "name": "Agogo PCM speed",
        "description": null,
        "cc": 52,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "PCM speed",
        "name": "Crash PCM speed",
        "description": null,
        "cc": 53,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Stutter",
        "name": "Stutter time",
        "description": null,
        "cc": 54,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Stutter",
        "name": "Stutter depth",
        "description": null,
        "cc": 55,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Decay",
        "name": "Tom decay",
        "description": null,
        "cc": 56,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Decay",
        "name": "Closed hat decay",
        "description": null,
        "cc": 57,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Decay",
        "name": "Open hat decay",
        "description": null,
        "cc": 58,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Other",
        "name": "Hat grain",
        "description": null,
        "cc": 59,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      }
    ]
  },

  // Source: vendor/pencilresearch-midi/KORG/volca drum.csv
  "korg-volca-drum": {
    "manufacturer": "KORG",
    "device": "volca drum",
    "slug": "korg-volca-drum",
    "parameters": [
      {
        "section": "General",
        "name": "Pan",
        "description": null,
        "cc": 10,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Select",
        "name": "Select 1",
        "description": null,
        "cc": 14,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Select",
        "name": "Select 2",
        "description": null,
        "cc": 15,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Select",
        "name": "Select 1-2",
        "description": null,
        "cc": 16,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Level",
        "name": "Level 1",
        "description": null,
        "cc": 17,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Level",
        "name": "Level 2",
        "description": null,
        "cc": 18,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Level",
        "name": "Level 1-2",
        "description": null,
        "cc": 19,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelope generator",
        "name": "EG attack 1",
        "description": null,
        "cc": 20,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelope generator",
        "name": "EG attack 2",
        "description": null,
        "cc": 21,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelope generator",
        "name": "EG attack 1-2",
        "description": null,
        "cc": 22,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelope generator",
        "name": "EG release 1",
        "description": null,
        "cc": 23,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelope generator",
        "name": "EG release 2",
        "description": null,
        "cc": 24,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelope generator",
        "name": "EG release 1-2",
        "description": null,
        "cc": 25,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Pitch",
        "name": "Pitch 1",
        "description": null,
        "cc": 26,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Pitch",
        "name": "Pitch 2",
        "description": null,
        "cc": 27,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Pitch",
        "name": "Pitch 1-2",
        "description": null,
        "cc": 28,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Mod",
        "name": "Mod amount 1",
        "description": null,
        "cc": 29,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Mod",
        "name": "Mod amount 2",
        "description": null,
        "cc": 30,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Mod",
        "name": "Mod amount 1-2",
        "description": null,
        "cc": 31,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Mod",
        "name": "Mod rate 1",
        "description": null,
        "cc": 46,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Mod",
        "name": "Mod rate 2",
        "description": null,
        "cc": 47,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Mod",
        "name": "Mod rate 1-2",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Bit reduction",
        "description": null,
        "cc": 49,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Fold",
        "description": null,
        "cc": 50,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Drive",
        "description": null,
        "cc": 51,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Dry gain",
        "description": null,
        "cc": 52,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Send",
        "description": null,
        "cc": 103,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Waveguide model",
        "description": null,
        "cc": 116,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Decay",
        "description": null,
        "cc": 117,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Body",
        "description": null,
        "cc": 118,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Tune",
        "description": null,
        "cc": 119,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      }
    ]
  },

  // Source: vendor/pencilresearch-midi/KORG/volca fm.csv
  "korg-volca-fm": {
    "manufacturer": "KORG",
    "device": "volca fm",
    "slug": "korg-volca-fm",
    "parameters": [
      {
        "section": "General",
        "name": "Transpose",
        "description": null,
        "cc": 40,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "centered",
        "usage": null,
        "notes": "-36 to +36 semitones (TRANSPS NOTE) or -3 to +3 octaves",
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Velocity",
        "description": null,
        "cc": 41,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Modulator attack",
        "description": null,
        "cc": 42,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Modulator decay",
        "description": null,
        "cc": 43,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Carrier attack",
        "description": null,
        "cc": 44,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Carrier decay",
        "description": null,
        "cc": 45,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "LFO rate",
        "description": null,
        "cc": 46,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "LFO pitch depth",
        "description": null,
        "cc": 47,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Algorithm",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Arpeggiator type",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Arpeggiator div",
        "description": null,
        "cc": 50,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      }
    ]
  },

  // Source: vendor/pencilresearch-midi/KORG/volca keys.csv
  "korg-volca-keys": {
    "manufacturer": "KORG",
    "device": "volca keys",
    "slug": "korg-volca-keys",
    "parameters": [
      {
        "section": "VCO",
        "name": "Portamento",
        "description": null,
        "cc": 5,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Expression",
        "description": null,
        "cc": 11,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Voice",
        "description": null,
        "cc": 40,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": "0-12: Poly; 13-37: Unison; 38-62: Octave; 63-87: Fifth; 88-112: Unison ring; 113-127: Poly ring",
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Octave",
        "description": null,
        "cc": 41,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": "0-21: 32'; 22-43: 16'; 44-65: 8'; 66-87: 4'; 88-109: 2'; 110-127: 1'",
        "notes": null,
        "nrpn": null
      },
      {
        "section": "VCO",
        "name": "Detune",
        "description": null,
        "cc": 42,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "VCO",
        "name": "VCO EG depth",
        "description": null,
        "cc": 43,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "EG",
        "name": "Attack",
        "description": null,
        "cc": 49,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "EG",
        "name": "Decay/release",
        "description": null,
        "cc": 50,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "EG",
        "name": "Sustain",
        "description": null,
        "cc": 51,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "VCF",
        "name": "Cutoff",
        "description": null,
        "cc": 44,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "VCF",
        "name": "VCF EG intensity",
        "description": null,
        "cc": 45,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "LFO",
        "name": "Rate",
        "description": null,
        "cc": 46,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "LFO",
        "name": "Pitch intensity",
        "description": null,
        "cc": 47,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "LFO",
        "name": "Cutoff intensity",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Delay",
        "name": "Delay time",
        "description": null,
        "cc": 52,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Delay",
        "name": "Delay feedback",
        "description": null,
        "cc": 53,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      }
    ]
  },

  // Source: vendor/pencilresearch-midi/KORG/volca kick.csv
  "korg-volca-kick": {
    "manufacturer": "KORG",
    "device": "volca kick",
    "slug": "korg-volca-kick",
    "parameters": [
      {
        "section": "General",
        "name": "Pulse color",
        "description": null,
        "cc": 40,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Pulse level",
        "description": null,
        "cc": 41,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Amp attack",
        "description": null,
        "cc": 42,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Amp decay",
        "description": null,
        "cc": 43,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Drive",
        "description": null,
        "cc": 44,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Tone",
        "description": null,
        "cc": 45,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Resonator pitch",
        "description": null,
        "cc": 46,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Resonator bend",
        "description": null,
        "cc": 47,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Resonator time",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "General",
        "name": "Accent",
        "description": null,
        "cc": 49,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      }
    ]
  },

  // Source: vendor/pencilresearch-midi/KORG/volca nubass.csv
  "korg-volca-nubass": {
    "manufacturer": "KORG",
    "device": "volca nubass",
    "slug": "korg-volca-nubass",
    "parameters": [
      {
        "section": "Vacuum tube oscillator",
        "name": "VTO pitch",
        "description": null,
        "cc": 40,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Vacuum tube oscillator",
        "name": "VTO saturation",
        "description": null,
        "cc": 41,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Vacuum tube oscillator",
        "name": "VTO level",
        "description": null,
        "cc": 42,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Filter",
        "name": "VCF cutoff",
        "description": null,
        "cc": 43,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Filter",
        "name": "VCF peak",
        "description": null,
        "cc": 44,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Filter",
        "name": "VCF attack",
        "description": null,
        "cc": 45,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Filter",
        "name": "VCF decay",
        "description": null,
        "cc": 46,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Filter",
        "name": "VCF EG intensity",
        "description": null,
        "cc": 47,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Other",
        "name": "Accent",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "LFO",
        "name": "LFO rate",
        "description": null,
        "cc": 49,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "LFO",
        "name": "LFO intensity",
        "description": null,
        "cc": 50,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      }
    ]
  },

  // Source: vendor/pencilresearch-midi/KORG/volca sample.csv
  "korg-volca-sample": {
    "manufacturer": "KORG",
    "device": "volca sample",
    "slug": "korg-volca-sample",
    "parameters": [
      {
        "section": "Sample",
        "name": "Level",
        "description": null,
        "cc": 7,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Sample",
        "name": "Pan",
        "description": null,
        "cc": 10,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Sample",
        "name": "Sample start point",
        "description": null,
        "cc": 40,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Sample",
        "name": "Sample length",
        "description": null,
        "cc": 41,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Sample",
        "name": "Hi cutoff",
        "description": null,
        "cc": 42,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Sample",
        "name": "Speed",
        "description": null,
        "cc": 43,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelopes",
        "name": "Pitch EG intensity",
        "description": null,
        "cc": 44,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelopes",
        "name": "Pitch EG attack",
        "description": null,
        "cc": 45,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelopes",
        "name": "Pitch EG decay",
        "description": null,
        "cc": 46,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelopes",
        "name": "Amp EG attack",
        "description": null,
        "cc": 47,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      },
      {
        "section": "Envelopes",
        "name": "Amp EG decay",
        "description": null,
        "cc": 48,
        "ccRange": {
          "min": 0,
          "max": 127
        },
        "ccDefault": null,
        "orientation": "0-based",
        "usage": null,
        "notes": null,
        "nrpn": null
      }
    ]
  },

};

/** Slug list, sorted. Useful for inspector enumeration / debugging. */
export const DEVICE_SLUGS: string[] = Object.keys(DEVICES).sort();
