#!/usr/bin/env node
// Bundle packages/core + packages/transport-spectacles-ws into a single .ts
// file that Lens Studio can load directly (LS can't import from node_modules).
//
// This is intentionally minimal: it concatenates source files in dependency
// order and strips intra-bundle imports. Anything more (true bundling, tree
// shaking, dead-code elimination) would require esbuild/rollup; v1 doesn't
// need it.

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');

const sources = [
  'packages/core/src/messages.ts',
  'packages/core/src/state.ts',
  'packages/core/src/transport.ts',
  'packages/core/src/client.ts',
  'packages/transport-spectacles-ws/src/index.ts',
];

const header = `// AUTO-GENERATED by scripts/build-lens.mjs — DO NOT EDIT BY HAND.
// Source of truth: packages/core + packages/transport-spectacles-ws.
// Regenerate via: npm run build:lens
`;

function stripImports(src) {
  // Drop intra-bundle imports: anything from a relative path or from another
  // workspace package. Preserve type-only re-exports as needed (we remove
  // imports entirely; declared types in this single file replace them).
  return src
    .split('\n')
    .filter((line) => {
      const trimmed = line.trim();
      if (trimmed.startsWith('import ') && /from\s+['"](\.\/|\.\.\/|@midi-bleep-bop\/)/.test(trimmed))
        return false;
      // also drop multi-line `import { ... } from '...';` blocks — they all end with `;`
      return true;
    })
    .join('\n');
}

const parts = sources.map((rel) => {
  const full = join(repoRoot, rel);
  const src = readFileSync(full, 'utf8');
  return `// ─── ${rel} ${'─'.repeat(Math.max(0, 60 - rel.length))}\n${stripImports(src)}`;
});

// Multi-line imports may span lines; do a second pass to remove any that survived.
const combined = [header, ...parts].join('\n');
const cleaned = combined.replace(
  /^import\s+(?:type\s+)?\{[^}]*\}\s+from\s+['"](?:\.\.?\/|@midi-bleep-bop\/)[^'"]+['"];?\s*$/gm,
  '',
);

const outDir = join(repoRoot, 'lens/MidiBleepBop.lspkg/Scripts');
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, 'MidiBleepBop.ts');
writeFileSync(outPath, cleaned);

const lines = cleaned.split('\n').length;
process.stdout.write(`wrote ${outPath} (${lines} lines)\n`);
