// AUTO-GENERATED by scripts/build-lens.mjs — DO NOT EDIT BY HAND.
// Source of truth: packages/core + packages/transport-spectacles-ws.
// Regenerate via: npm run build:lens

// ─── packages/core/src/messages.ts ───────────────────────────────
export type NoteOn = { type: 'noteOn'; channel: number; note: number; velocity: number };
export type NoteOff = { type: 'noteOff'; channel: number; note: number; velocity: number };
export type CC = { type: 'cc'; channel: number; controller: number; value: number };
export type ProgramChange = { type: 'programChange'; channel: number; program: number };
export type PitchBend = { type: 'pitchBend'; channel: number; value: number };
export type ChannelPressure = { type: 'channelPressure'; channel: number; pressure: number };
export type PolyPressure = { type: 'polyPressure'; channel: number; note: number; pressure: number };
export type Raw = { type: 'raw'; bytes: Uint8Array };

export type MidiMessage =
  | NoteOn
  | NoteOff
  | CC
  | ProgramChange
  | PitchBend
  | ChannelPressure
  | PolyPressure
  | Raw;

export function parseMessage(bytes: Uint8Array): MidiMessage {
  if (bytes.length === 0) return { type: 'raw', bytes };

  const status = bytes[0]!;
  if ((status & 0x80) === 0) return { type: 'raw', bytes };

  const channel = status & 0x0f;
  const kind = status & 0xf0;

  switch (kind) {
    case 0x80:
      if (bytes.length < 3) return { type: 'raw', bytes };
      return { type: 'noteOff', channel, note: bytes[1]!, velocity: bytes[2]! };

    case 0x90: {
      if (bytes.length < 3) return { type: 'raw', bytes };
      const note = bytes[1]!;
      const velocity = bytes[2]!;
      if (velocity === 0) return { type: 'noteOff', channel, note, velocity: 0 };
      return { type: 'noteOn', channel, note, velocity };
    }

    case 0xa0:
      if (bytes.length < 3) return { type: 'raw', bytes };
      return { type: 'polyPressure', channel, note: bytes[1]!, pressure: bytes[2]! };

    case 0xb0:
      if (bytes.length < 3) return { type: 'raw', bytes };
      return { type: 'cc', channel, controller: bytes[1]!, value: bytes[2]! };

    case 0xc0:
      if (bytes.length < 2) return { type: 'raw', bytes };
      return { type: 'programChange', channel, program: bytes[1]! };

    case 0xd0:
      if (bytes.length < 2) return { type: 'raw', bytes };
      return { type: 'channelPressure', channel, pressure: bytes[1]! };

    case 0xe0: {
      if (bytes.length < 3) return { type: 'raw', bytes };
      const value = (bytes[1]! | (bytes[2]! << 7)) - 8192;
      return { type: 'pitchBend', channel, value };
    }

    default:
      return { type: 'raw', bytes };
  }
}

export function encodeMessage(msg: MidiMessage): Uint8Array {
  switch (msg.type) {
    case 'noteOn':
      return new Uint8Array([0x90 | (msg.channel & 0x0f), msg.note & 0x7f, msg.velocity & 0x7f]);
    case 'noteOff':
      return new Uint8Array([0x80 | (msg.channel & 0x0f), msg.note & 0x7f, msg.velocity & 0x7f]);
    case 'cc':
      return new Uint8Array([0xb0 | (msg.channel & 0x0f), msg.controller & 0x7f, msg.value & 0x7f]);
    case 'programChange':
      return new Uint8Array([0xc0 | (msg.channel & 0x0f), msg.program & 0x7f]);
    case 'pitchBend': {
      const v = (msg.value + 8192) & 0x3fff;
      return new Uint8Array([0xe0 | (msg.channel & 0x0f), v & 0x7f, (v >> 7) & 0x7f]);
    }
    case 'channelPressure':
      return new Uint8Array([0xd0 | (msg.channel & 0x0f), msg.pressure & 0x7f]);
    case 'polyPressure':
      return new Uint8Array([0xa0 | (msg.channel & 0x0f), msg.note & 0x7f, msg.pressure & 0x7f]);
    case 'raw':
      return msg.bytes;
  }
}

// ─── packages/core/src/state.ts ──────────────────────────────────

export class ChannelState {
  readonly heldNotes = new Map<number, number>();
  readonly cc = new Map<number, number>();
  program: number | undefined = undefined;
  pitchBend = 0;
  channelPressure = 0;
}

export class MidiState {
  private readonly channels: ChannelState[] = [];

  constructor() {
    for (let i = 0; i < 16; i++) this.channels.push(new ChannelState());
  }

  get(channel: number): ChannelState | undefined {
    return this.channels[channel];
  }

  apply(msg: MidiMessage): void {
    if (msg.type === 'raw') return;
    const ch = this.channels[msg.channel];
    if (!ch) return;

    switch (msg.type) {
      case 'noteOn':
        ch.heldNotes.set(msg.note, msg.velocity);
        break;
      case 'noteOff':
        ch.heldNotes.delete(msg.note);
        break;
      case 'cc':
        ch.cc.set(msg.controller, msg.value);
        break;
      case 'programChange':
        ch.program = msg.program;
        break;
      case 'pitchBend':
        ch.pitchBend = msg.value;
        break;
      case 'channelPressure':
        ch.channelPressure = msg.pressure;
        break;
      case 'polyPressure':
        break;
    }
  }

  heldNotes(channel?: number): number[] {
    if (channel !== undefined) {
      const ch = this.channels[channel];
      return ch ? [...ch.heldNotes.keys()].sort((a, b) => a - b) : [];
    }
    const all: number[] = [];
    for (const ch of this.channels) all.push(...ch.heldNotes.keys());
    return [...new Set(all)].sort((a, b) => a - b);
  }
}

// ─── packages/core/src/transport.ts ──────────────────────────────
export type ConnectionState = 'connecting' | 'open' | 'closed';

export interface Transport {
  send(data: Uint8Array): void;
  onMessage(handler: (data: Uint8Array) => void): void;
  onStateChange(handler: (state: ConnectionState) => void): void;
  close(): void;
}

export class MockTransport implements Transport {
  readonly sent: Uint8Array[] = [];
  private messageHandler: ((data: Uint8Array) => void) | undefined;
  private stateHandler: ((state: ConnectionState) => void) | undefined;
  private currentState: ConnectionState = 'open';

  send(data: Uint8Array): void {
    this.sent.push(data);
  }

  onMessage(handler: (data: Uint8Array) => void): void {
    this.messageHandler = handler;
  }

  onStateChange(handler: (state: ConnectionState) => void): void {
    this.stateHandler = handler;
    handler(this.currentState);
  }

  close(): void {
    this.setState('closed');
  }

  // Test helpers

  simulateMessage(data: Uint8Array): void {
    this.messageHandler?.(data);
  }

  setState(state: ConnectionState): void {
    if (this.currentState === state) return;
    this.currentState = state;
    this.stateHandler?.(state);
  }
}

// ─── packages/core/src/client.ts ─────────────────────────────────

export type Unsubscribe = () => void;

type EventPayloads = {
  message: MidiMessage;
  noteOn: NoteOn;
  noteOff: NoteOff;
  cc: CC;
  programChange: ProgramChange;
  pitchBend: PitchBend;
  channelPressure: ChannelPressure;
  connect: void;
  disconnect: void;
};

type EventName = keyof EventPayloads;

export class MidiClient {
  private readonly listeners = new Map<EventName, Set<(payload: unknown) => void>>();
  private readonly ccChangeListeners = new Map<string, Set<(value: number, previous: number | undefined) => void>>();
  private readonly noteHeldListeners = new Map<string, Set<(held: boolean, velocity: number) => void>>();
  private readonly programChangeListeners = new Map<number, Set<(program: number) => void>>();
  private readonly midiState = new MidiState();
  private currentState: ConnectionState = 'closed';
  private connectWaiters: Array<{ resolve: () => void; reject: (e: Error) => void }> = [];

  constructor(private readonly transport: Transport) {
    this.transport.onMessage((bytes) => this.handleIncoming(bytes));
    this.transport.onStateChange((state) => this.handleStateChange(state));
  }

  get state(): ConnectionState {
    return this.currentState;
  }

  get connected(): boolean {
    return this.currentState === 'open';
  }

  connect(): Promise<void> {
    if (this.currentState === 'open') return Promise.resolve();
    return new Promise<void>((resolve, reject) => {
      this.connectWaiters.push({ resolve, reject });
    });
  }

  close(): void {
    this.transport.close();
  }

  sendNoteOn(channel: number, note: number, velocity: number): void {
    this.send({ type: 'noteOn', channel, note, velocity });
  }

  sendNoteOff(channel: number, note: number, velocity = 0): void {
    this.send({ type: 'noteOff', channel, note, velocity });
  }

  sendCC(channel: number, controller: number, value: number): void {
    this.send({ type: 'cc', channel, controller, value });
  }

  sendProgramChange(channel: number, program: number): void {
    this.send({ type: 'programChange', channel, program });
  }

  sendPitchBend(channel: number, value: number): void {
    this.send({ type: 'pitchBend', channel, value });
  }

  sendChannelPressure(channel: number, pressure: number): void {
    this.send({ type: 'channelPressure', channel, pressure });
  }

  send(msg: MidiMessage): void {
    this.transport.send(encodeMessage(msg));
  }

  sendRaw(bytes: Uint8Array): void {
    this.transport.send(bytes);
  }

  on<E extends EventName>(event: E, handler: (payload: EventPayloads[E]) => void): Unsubscribe {
    let bucket = this.listeners.get(event);
    if (!bucket) {
      bucket = new Set();
      this.listeners.set(event, bucket);
    }
    bucket.add(handler as (payload: unknown) => void);
    return () => bucket.delete(handler as (payload: unknown) => void);
  }

  heldNotes(channel?: number): number[] {
    return this.midiState.heldNotes(channel);
  }

  ccValue(channel: number, controller: number): number | undefined {
    return this.midiState.get(channel)?.cc.get(controller);
  }

  programNumber(channel: number): number | undefined {
    return this.midiState.get(channel)?.program;
  }

  pitchBend(channel: number): number {
    return this.midiState.get(channel)?.pitchBend ?? 0;
  }

  channelPressure(channel: number): number {
    return this.midiState.get(channel)?.channelPressure ?? 0;
  }

  onCCChange(
    channel: number,
    controller: number,
    handler: (value: number, previous: number | undefined) => void,
  ): Unsubscribe {
    const key = `${channel}:${controller}`;
    let bucket = this.ccChangeListeners.get(key);
    if (!bucket) {
      bucket = new Set();
      this.ccChangeListeners.set(key, bucket);
    }
    bucket.add(handler);
    return () => bucket.delete(handler);
  }

  onNoteHeld(
    channel: number,
    note: number,
    handler: (held: boolean, velocity: number) => void,
  ): Unsubscribe {
    const key = `${channel}:${note}`;
    let bucket = this.noteHeldListeners.get(key);
    if (!bucket) {
      bucket = new Set();
      this.noteHeldListeners.set(key, bucket);
    }
    bucket.add(handler);
    return () => bucket.delete(handler);
  }

  onProgramChange(channel: number, handler: (program: number) => void): Unsubscribe {
    let bucket = this.programChangeListeners.get(channel);
    if (!bucket) {
      bucket = new Set();
      this.programChangeListeners.set(channel, bucket);
    }
    bucket.add(handler);
    return () => bucket.delete(handler);
  }

  private handleIncoming(bytes: Uint8Array): void {
    const msg = parseMessage(bytes);
    const prevState = this.snapshotForChange(msg);
    this.midiState.apply(msg);
    this.emit('message', msg);
    this.emitTyped(msg);
    this.emitStateChanges(msg, prevState);
  }

  private handleStateChange(state: ConnectionState): void {
    const wasOpen = this.currentState === 'open';
    this.currentState = state;

    if (state === 'open') {
      const waiters = this.connectWaiters;
      this.connectWaiters = [];
      for (const w of waiters) w.resolve();
      this.emit('connect', undefined);
    } else if (state === 'closed' && wasOpen) {
      this.emit('disconnect', undefined);
    } else if (state === 'closed') {
      const waiters = this.connectWaiters;
      this.connectWaiters = [];
      for (const w of waiters) w.reject(new Error('Transport closed before connection opened'));
    }
  }

  private emit<E extends EventName>(event: E, payload: EventPayloads[E]): void {
    const bucket = this.listeners.get(event);
    if (!bucket) return;
    for (const h of bucket) h(payload);
  }

  private emitTyped(msg: MidiMessage): void {
    switch (msg.type) {
      case 'noteOn':
        this.emit('noteOn', msg);
        break;
      case 'noteOff':
        this.emit('noteOff', msg);
        break;
      case 'cc':
        this.emit('cc', msg);
        break;
      case 'programChange':
        this.emit('programChange', msg);
        break;
      case 'pitchBend':
        this.emit('pitchBend', msg);
        break;
      case 'channelPressure':
        this.emit('channelPressure', msg);
        break;
    }
  }

  private snapshotForChange(msg: MidiMessage): { ccPrev?: number; wasHeld?: boolean; prevProgram?: number } {
    if (msg.type === 'cc') {
      return { ccPrev: this.midiState.get(msg.channel)?.cc.get(msg.controller) };
    }
    if (msg.type === 'noteOn' || msg.type === 'noteOff') {
      return { wasHeld: this.midiState.get(msg.channel)?.heldNotes.has(msg.note) ?? false };
    }
    if (msg.type === 'programChange') {
      return { prevProgram: this.midiState.get(msg.channel)?.program };
    }
    return {};
  }

  private emitStateChanges(
    msg: MidiMessage,
    prev: { ccPrev?: number; wasHeld?: boolean; prevProgram?: number },
  ): void {
    if (msg.type === 'cc') {
      if (prev.ccPrev === msg.value) return;
      const bucket = this.ccChangeListeners.get(`${msg.channel}:${msg.controller}`);
      if (!bucket) return;
      for (const h of bucket) h(msg.value, prev.ccPrev);
      return;
    }

    if (msg.type === 'noteOn') {
      if (prev.wasHeld) return;
      const bucket = this.noteHeldListeners.get(`${msg.channel}:${msg.note}`);
      if (!bucket) return;
      for (const h of bucket) h(true, msg.velocity);
      return;
    }

    if (msg.type === 'noteOff') {
      if (!prev.wasHeld) return;
      const bucket = this.noteHeldListeners.get(`${msg.channel}:${msg.note}`);
      if (!bucket) return;
      for (const h of bucket) h(false, msg.velocity);
      return;
    }

    if (msg.type === 'programChange') {
      if (prev.prevProgram === msg.program) return;
      const bucket = this.programChangeListeners.get(msg.channel);
      if (!bucket) return;
      for (const h of bucket) h(msg.program);
    }
  }
}

// ─── packages/transport-spectacles-ws/src/index.ts ───────────────

// Lens Studio's WebSocket type is intentionally not pulled in here — the file is
// compiled both for tsc type-checking (where these types don't exist) and for
// embedding into a Lens Studio project. We rely on runtime duck-typing via
// `require("LensStudio:InternetModule")`.
//
// The shape we depend on:
//   internetModule.createWebSocket(url: string): WebSocket
//   WebSocket: { onopen, onclose, onerror, onmessage, send, close, binaryType, readyState }
//   message event: { data: Blob | string }, with Blob.bytes() returning a Promise<Uint8Array>.

interface LSWebSocket {
  binaryType: string;
  readyState: number;
  onopen: ((event: unknown) => void) | null;
  onclose: ((event: { code: number; reason: string; wasClean: boolean }) => void) | null;
  onerror: ((event: unknown) => void) | null;
  onmessage: ((event: { data: unknown }) => void) | null;
  send(data: Uint8Array | string): void;
  close(): void;
}

interface LSInternetModule {
  createWebSocket(url: string, protocols?: string | string[]): LSWebSocket;
}

interface LSBlob {
  bytes(): Promise<Uint8Array>;
}

function isBlob(value: unknown): value is LSBlob {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof (value as { bytes?: unknown }).bytes === 'function'
  );
}

export type Cancel = () => void;
export type Schedule = (callback: () => void, delayMs: number) => Cancel;

export interface SpectaclesWebSocketTransportOptions {
  url: string;
  reconnect?: boolean;
  reconnectMaxMs?: number;
  /**
   * Optional override for the InternetModule. By default the transport calls
   * `require("LensStudio:InternetModule")` lazily on the first connection.
   * Pass a custom module here for tests or for non-Lens-Studio embeddings.
   */
  internetModule?: LSInternetModule;
  /**
   * How to schedule a callback after a delay. Lens Studio does not expose
   * `setTimeout`; the @component wrapper (`MidiClientComponent`) supplies a
   * `schedule` backed by Lens Studio's `DelayedCallbackEvent`. Outside Lens
   * Studio the transport falls back to `globalThis.setTimeout` if present.
   * Setting this to `null` disables reconnect.
   */
  schedule?: Schedule | null;
  /**
   * Optional log function. Defaults to `print` if available (Lens Studio), then
   * `console.log`. Set to `() => {}` to silence.
   */
  log?: (msg: string) => void;
}

export class SpectaclesWebSocketTransport implements Transport {
  private socket: LSWebSocket | undefined;
  private messageHandler: ((data: Uint8Array) => void) | undefined;
  private stateHandler: ((state: ConnectionState) => void) | undefined;
  private currentState: ConnectionState = 'closed';
  private reconnectAttempt = 0;
  private cancelReconnect: Cancel | undefined;
  private closed = false;
  private readonly log: (msg: string) => void;
  private readonly schedule: Schedule | null;

  constructor(private readonly options: SpectaclesWebSocketTransportOptions) {
    this.log = options.log ?? defaultLog;
    this.schedule = options.schedule === undefined ? defaultSchedule() : options.schedule;
    this.openSocket();
  }

  send(data: Uint8Array): void {
    if (!this.socket) return;
    // 1 = OPEN
    if (this.socket.readyState !== 1) return;
    try {
      this.socket.send(data);
    } catch (e) {
      this.log('[midi-bleep-bop] send failed: ' + String(e));
    }
  }

  onMessage(handler: (data: Uint8Array) => void): void {
    this.messageHandler = handler;
  }

  onStateChange(handler: (state: ConnectionState) => void): void {
    this.stateHandler = handler;
    handler(this.currentState);
  }

  close(): void {
    this.closed = true;
    if (this.cancelReconnect) {
      this.cancelReconnect();
      this.cancelReconnect = undefined;
    }
    try {
      this.socket?.close();
    } catch {
      // ignore
    }
    this.socket = undefined;
    this.setState('closed');
  }

  private openSocket(): void {
    this.setState('connecting');
    let module = this.options.internetModule;
    if (!module) {
      try {
        // Lens Studio runtime require — intentionally not statically imported.
        // eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
        module = (globalThis as { require?: (name: string) => unknown }).require?.(
          'LensStudio:InternetModule',
        ) as LSInternetModule | undefined;
      } catch (e) {
        this.log('[midi-bleep-bop] could not resolve LensStudio:InternetModule: ' + String(e));
      }
    }
    if (!module) {
      this.log('[midi-bleep-bop] InternetModule unavailable; transport stays closed');
      this.setState('closed');
      return;
    }

    let socket: LSWebSocket;
    try {
      socket = module.createWebSocket(this.options.url);
    } catch (e) {
      this.log('[midi-bleep-bop] createWebSocket failed: ' + String(e));
      this.setState('closed');
      if (!this.closed && this.options.reconnect !== false) this.scheduleReconnect();
      return;
    }

    socket.binaryType = 'blob';
    this.socket = socket;

    socket.onopen = (): void => {
      this.reconnectAttempt = 0;
      this.setState('open');
    };

    socket.onmessage = (event: { data: unknown }): void => {
      const data = event.data;
      if (typeof data === 'string') {
        // text frames are ignored at the wire-protocol level
        return;
      }
      if (!isBlob(data)) return;
      data
        .bytes()
        .then((bytes) => {
          if (bytes.length === 0) return;
          this.messageHandler?.(bytes);
        })
        .catch((e: unknown) => {
          this.log('[midi-bleep-bop] failed to decode binary frame: ' + String(e));
        });
    };

    socket.onerror = (event: unknown): void => {
      this.log('[midi-bleep-bop] socket error: ' + String(event));
    };

    socket.onclose = (event: { code: number; reason: string; wasClean: boolean }): void => {
      this.socket = undefined;
      this.log(
        '[midi-bleep-bop] socket closed (code=' +
          String(event.code) +
          ', clean=' +
          String(event.wasClean) +
          ')',
      );
      if (this.closed) return;
      this.setState('closed');
      if (this.options.reconnect === false) return;
      this.scheduleReconnect();
    };
  }

  private scheduleReconnect(): void {
    if (!this.schedule) return;
    const max = this.options.reconnectMaxMs ?? 5000;
    const backoffs = [500, 1000, 2000, 5000];
    const delay = Math.min(backoffs[Math.min(this.reconnectAttempt, backoffs.length - 1)]!, max);
    this.reconnectAttempt++;
    this.cancelReconnect = this.schedule(() => {
      this.cancelReconnect = undefined;
      if (!this.closed) this.openSocket();
    }, delay);
  }

  private setState(state: ConnectionState): void {
    if (this.currentState === state) return;
    this.currentState = state;
    this.stateHandler?.(state);
  }
}

function defaultLog(msg: string): void {
  // Prefer Lens Studio's print(); fall back to console.log when running outside.
  const g = globalThis as { print?: (msg: string) => void; console?: { log?: (...args: unknown[]) => void } };
  if (typeof g.print === 'function') {
    g.print(msg);
  } else if (g.console && typeof g.console.log === 'function') {
    g.console.log(msg);
  }
}

function defaultSchedule(): Schedule | null {
  const g = globalThis as {
    setTimeout?: (cb: () => void, ms: number) => unknown;
    clearTimeout?: (handle: unknown) => void;
  };
  if (typeof g.setTimeout !== 'function' || typeof g.clearTimeout !== 'function') return null;
  return (callback, delayMs) => {
    const handle = g.setTimeout!(callback, delayMs);
    return () => g.clearTimeout!(handle);
  };
}
